name: '[PR] Build'

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: 'true'
      
      - name: Setup Supplychain Security
        uses: projectkeas/.engineering/.github/actions/setup-supplychain-security@main

      - name: Build & Verify
        uses: projectkeas/.engineering/.github/actions/go-build@main
        with:
          appName: ${{ github.repository }}